### ISSUE TITLE
[Existing API Name] : Password Generator API

### ISSUE THREAD

**Issue by dhruvishavaghani** [developer-student-clubs/APIVerse#7] opened 2023-09-30 18:40 UTC
### Brief Description 🤓

This API is used to generate strong passwords. Users can generate a strong password on a single that contains uppercase, and lowercase letters, numbers, and symbols as well.

### Provide reference!

Referenced From: API Ninja
https://api-ninjas.com/api/passwordgenerator

### Select the open source program you are contributing to

hacktoberfest-23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

**Comment by dishamodi0910** [comment] 2023-09-30 18:40
Greetings @dhruvishavaghani🎀 ! , We are excited to have you dive into another issue with us!🚀
Your involvement in our project has been invaluable, and we're confident that your skills and insights will help us conquer this challenge😇. <h2> Use command /gdsc to self assign the issue. </h2> This issue represents an exciting opportunity for us to improve and enhance our project, and we are thrilled to have you on board.
 We request you to follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Looking for your PR soon! 
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN).❣️

**Comment by dishamodi0910** [comment] 2023-09-30 19:23
Hey @dhruvishavaghani, The issue is already assigned and couldn't be assigned to you again.You can work on some other issue or create your own issue.🚀💗

**Comment by dishamodi0910** [comment] 2023-10-01 03:25
@dhruvishavaghani 🚀

**Comment by dishamodi0910** [comment] 2023-10-01 15:24
Hey @dhruvishavaghani ! I wanted to inform you that we have closed issue.Thank you for your understanding, and we look forward to your continued engagement with our repository🤗.
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN). 
Thank you! ❣️
Happy Coding! ✨
Will See you soon❣️

**Closed** 2023-10-01 15:24 UTC
Labels: existing-api, hacktoberfest, wow
